---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Writing your lab"
      solveButton: true

tabs:
  - name: ">_ Terminal 1"
    url: /wetty
  - name: "Visual Studio Code"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel/projects/quarkus/getting-started
    external: false
  - name: ">_ Terminal 2"
    url: /wetty
  - name: "Dev UI"
    url: https://quarkus-${guid}.${domain}/q/dev
    external: false
  - name: "Cockpit"
    url: https://cockpit-${guid}.${domain}/
    external: false
