---

antora:
  name: modules
  dir: www
  modules:
    - name: module-01
      label: "Writing your lab"
      solveButton: true

tabs:
  - name: ">_ terminal 1"
    url: /wetty
    secondary_url: /wetty
  - name: "Visual Studio Code"
    url: https://vscode-${guid}.${domain}/?folder=/home/rhel
    external: false
  - name: ">_ terminal 2"
    url: /wetty
  - name: "Dev UI"
    url: https://quarkus-${guid}.${domain}/q/dev
    external: false
  - name: "Asciidoc Doc"
    url: https://docs.asciidoctor.org/asciidoc/latest/syntax-quick-reference/
    external: true
