---
# By default egress traffic is not allowed, define below the ports allowed.
ingress:
  - ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 9090
egress:
  - ports:
      - protocol: TCP
        port: 80
      - protocol: TCP
        port: 443
      - protocol: TCP
        port: 8080
      - protocol: TCP
        port: 9090
