---
containers: []
virtualmachines:
  - name: terminal
    image: "rhel-9.6"
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: quarkus
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: quarkus
    routes:
      - name: quarkus
        host: quarkus
        service: quarkus
        targetPort: 8080
        tls: true
        tls_termination: Edge
  - name: "vscode"
    image: "devtools-ansible"
    memory: "8G"
    cores: 2
    image_size: "20Gi"
    disk_type: "scsi"
    bootloader: "efi"
    tags:
      - key: "AnsibleGroup"
        value: "isolated"
    networks:
      - default
    services:
      - name: vscode-8080
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: vscode
    routes:
      - name: vscode-8080
        host: vscode
        service: vscode-8080
        targetPort: 8080
        tls: true
        tls_termination: Edge
    userdata: |-
      #cloud-config
      user: rhel
      password: ansible123!
      chpasswd: { expire: False }
      runcmd:
        - echo "PasswordAuthentication yes" > /etc/ssh/sshd_config.d/50-cloud-init.conf
        - systemctl reload sshd
