---
containers: []
virtualmachines:
  - name: terminal
    image: "rhel-9.6"
    memory: "4G"
    cores: 1
    image_size: "40G"
    tags:
      - key: "AnsibleGroup"
        value: "bastions"
    networks:
      - default
    services:
      - name: quarkus
        ports:
          - port: 8080
            protocol: TCP
            targetPort: 8080
            name: quarkus
      - name: cockpit
        ports:
          - port: 9090
            protocol: TCP
            targetPort: 9090
            name: cockpit
    routes:
      - name: quarkus
        host: terminal
        service: quarkus
        targetPort: 8080
        tls: true
        tls_termination: Edge
      - name: cockpit
        host: terminal
        service: cockpit
        targetPort: 9090
        tls: true
        tls_termination: Edge
