---
- name: Create inventory
  hosts: localhost
  gather_facts: false
  tasks:
  - name: Add bastion host
    ansible.builtin.add_host:
      name: "{{ lookup('ansible.builtin.env', 'BASTION_HOST') }}"
      ansible_ssh_host: "{{ lookup('ansible.builtin.env', 'BASTION_HOST') }}"
      ansible_ssh_port: "{{ lookup('ansible.builtin.env', 'BASTION_PORT') }}"
      ansible_ssh_user: "{{ lookup('ansible.builtin.env', 'BASTION_USER') }}"
      ansible_ssh_pass: "{{ lookup('ansible.builtin.env', 'BASTION_PASSWORD') }}"
- name: Demo Playbook for the ansible-runner API
  hosts: all:!localhost
  gather_facts: false
  tasks:

  - ansible.builtin.wait_for_connection:
  - name: Simple debug task
    ansible.builtin.debug:
      msg: "Hello Runner"

  - name: Set config_host variable with ansible_host value
    set_fact:
      config_host: "{{ ansible_host }}"

  - name: Create a directory if it does not exist
    ansible.builtin.file:
      path: "/tmp/setup-scripts/"
      state: directory
      mode: '0755'

  - name: Check if setup-server.sh exists
    ansible.builtin.stat:
      path: "./setup-{{ config_host }}.sh"
    delegate_to: localhost
    register: r_script_test

  - name: Copy script file
    when: r_script_test.stat.exists
    copy:
      src: "./setup-{{ ansible_host }}.sh"
      dest: "/tmp/setup-scripts/setup-{{ ansible_host }}.sh"
    register: r_result

  - name: Execute module_stage-host.sh if it exists
    when: r_script_test.stat.exists
    shell: "sh -x /tmp/setup-scripts/setup-{{ ansible_host }}.sh > /tmp/setup-scripts/setup-{{ ansible_host }}.log 2>&1"
    become: true
    register: r_result

  - name: Output script result
    ansible.builtin.debug:
      var: r_result.stdout
    when: r_script_test.stat.exists

  - name: Write script result to file
    ansible.builtin.copy:
      content: "{{ r_result.stdout | default(r_result.stderr) | default(r_result) }}"
      dest: "/tmp/{{ ansible_host }}-setup-script.out"
    delegate_to: localhost
    when:
    - r_result is defined

  - name: Output script result
    ansible.builtin.debug:
      var: r_result
    when: r_result is defined

  - name: Fail if stage was failed
    ansible.builtin.fail:
      msg: "Setup failed"
    when:
    - r_result is defined
    - r_result.rc != 0
